# Ola Ride Insights

### Import Package

In [91]:
import pandas as pd

##3 Data loading using Pandas

In [92]:
url = (r"C:\Users\harin\OneDrive\Desktop\OLA RIDE PROJECT\OLA_DataSet.xlsx")
df = pd.read_excel(url)

In [93]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,NaN,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,203.0,30.0,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,238.0,130.0,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,NaN,NaN,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,252.0,80.0,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [94]:
df.tail()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,245.0,35.0,NaN,NaN,No,NaN,111,Cash,41,3.6,3.8,https://cdn-icons-png.flaticon.com/128/11409/1...
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,84.0,145.0,NaN,NaN,No,NaN,1097,UPI,17,4.3,3.3,https://cdn-icons-png.flaticon.com/128/16526/1...
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,35.0,75.0,NaN,NaN,No,NaN,2201,Cash,37,3.6,3.2,https://cdn-icons-png.flaticon.com/128/9983/99...
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,210.0,140.0,NaN,NaN,No,NaN,267,UPI,47,3.4,3.1,https://cdn-icons-png.flaticon.com/128/6839/68...
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,175.0,125.0,NaN,NaN,No,NaN,462,UPI,3,4.8,4.4,https://cdn-icons-png.flaticon.com/128/16526/1...

### Checking shape of dataset

In [95]:
df.shape

(103024, 20)

### Checking Null values

In [96]:
df.isnull()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,False,False,False,False,False,False,False,False,True,True,True,False,True,True,False,True,False,True,True,False
1,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,True,False,True,True,True,False,True,False,True,True,False
4,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False
103020,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False
103021,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False
103022,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False
103023,False,False,False,False,False,False,False,False,False,False,True,True,False,True,False,False,False,False,False,False

### Checking sum of null values in each column

In [97]:
df.isnull().sum()

Date                              0
Time                              0
Booking_ID                        0
Booking_Status                    0
Customer_ID                       0
Vehicle_Type                      0
Pickup_Location                   0
Drop_Location                     0
V_TAT                         39057
C_TAT                         39057
Canceled_Rides_by_Customer    92525
Canceled_Rides_by_Driver      84590
Incomplete_Rides              39057
Incomplete_Rides_Reason       99098
Booking_Value                     0
Payment_Method                39057
Ride_Distance                     0
Driver_Ratings                39057
Customer_Rating               39057
Vehicle Images                    0
dtype: int64

### Checking percentage of null values present in each column

In [98]:
100*df.isnull().sum()/df.shape[0]

Date                           0.000000
Time                           0.000000
Booking_ID                     0.000000
Booking_Status                 0.000000
Customer_ID                    0.000000
Vehicle_Type                   0.000000
Pickup_Location                0.000000
Drop_Location                  0.000000
V_TAT                         37.910584
C_TAT                         37.910584
Canceled_Rides_by_Customer    89.809171
Canceled_Rides_by_Driver      82.107082
Incomplete_Rides              37.910584
Incomplete_Rides_Reason       96.189237
Booking_Value                  0.000000
Payment_Method                37.910584
Ride_Distance                  0.000000
Driver_Ratings                37.910584
Customer_Rating               37.910584
Vehicle Images                 0.000000
dtype: float64

In [99]:
df.V_TAT.value_counts()

V_TAT
56.0     1670
196.0    1665
105.0    1652
168.0    1650
126.0    1644
224.0    1637
98.0     1632
63.0     1631
308.0    1630
84.0     1628
91.0     1624
77.0     1623
210.0    1615
70.0     1614
280.0    1611
133.0    1610
119.0    1609
42.0     1606
112.0    1603
154.0    1601
259.0    1597
203.0    1597
189.0    1596
182.0    1596
301.0    1594
266.0    1589
147.0    1585
217.0    1584
35.0     1584
175.0    1581
252.0    1571
245.0    1567
49.0     1564
273.0    1564
294.0    1555
287.0    1553
231.0    1543
238.0    1536
161.0    1532
140.0    1524
Name: count, dtype: int64

### V_TAT column is removed after analysis

In [100]:
df.drop('V_TAT',axis=1,inplace=True)

### C_TAT column is removed after analysis

In [101]:
df.drop('C_TAT',axis=1,inplace=True)

In [102]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,NaN,Personal & Car related issue,NaN,NaN,444,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/14183/1...
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,NaN,NaN,No,NaN,158,Cash,13,4.1,4.0,https://cdn-icons-png.flaticon.com/128/9983/99...
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,NaN,NaN,No,NaN,386,UPI,40,4.2,4.8,https://cdn-icons-png.flaticon.com/128/9983/99...
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,Driver is not moving towards pickup location,NaN,NaN,NaN,384,NaN,0,NaN,NaN,https://cdn-icons-png.flaticon.com/128/6839/68...
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,NaN,NaN,No,NaN,822,Credit Card,45,4.0,3.0,https://cdn-icons-png.flaticon.com/128/3202/32...

In [103]:
df.Booking_Status.value_counts()

Booking_Status
Success                 63967
Canceled by Driver      18434
Canceled by Customer    10499
Driver Not Found        10124
Name: count, dtype: int64

In [104]:
df.Payment_Method.value_counts()

Payment_Method
Cash           35022
UPI            25881
Credit Card     2435
Debit Card       629
Name: count, dtype: int64

### Incomplete Ride Reasons Analysis

The following code was used to analyze the frequency of incomplete ride reasons in the dataset

In [105]:
df['Incomplete_Rides_Reason'].value_counts(dropna=False)

Incomplete_Rides_Reason
NaN                  99098
Customer Demand       1601
Vehicle Breakdown     1591
Other Issue            734
Name: count, dtype: int64

### Handling Missing Values in Incomplete Ride Reasons

The following code replaces missing values in the `Incomplete_Rides_Reason` column with `"Completed Ride"`

In [106]:
df['Incomplete_Rides_Reason'] = (
    df['Incomplete_Rides_Reason']
    .fillna('Completed Ride')
)

### Customer Cancellation Analysis

The following code was used to analyze the frequency of customer ride cancellations

In [107]:
df.Canceled_Rides_by_Customer.value_counts(dropna=False)

Canceled_Rides_by_Customer
NaN                                             92525
Driver is not moving towards pickup location     3175
Driver asked to cancel                           2670
Change of plans                                  2081
AC is Not working                                1568
Wrong Address                                    1005
Name: count, dtype: int64

### Driver Cancellation Analysis

The following code was used to analyze the frequency of driver ride cancellations:

In [108]:
df['Canceled_Rides_by_Driver'].value_counts(dropna=False)

Canceled_Rides_by_Driver
NaN                                    84590
Personal & Car related issue            6542
Customer related issue                  5413
Customer was coughing/sick              3654
More than permitted people in there     2825
Name: count, dtype: int64

### Handling Missing Values in Incomplete Ride Reasons

The following code replaces missing values in the `Canceled_Rides_by_Driver` column with `"Not Canceled_Rides_by_Driver"`.

In [109]:
df['Canceled_Rides_by_Driver'] = (
    df['Canceled_Rides_by_Driver']
    .fillna('Not Cancelled by Driver')
)

In [110]:
df['Canceled_Rides_by_Customer'].value_counts(dropna=False)

Canceled_Rides_by_Customer
NaN                                             92525
Driver is not moving towards pickup location     3175
Driver asked to cancel                           2670
Change of plans                                  2081
AC is Not working                                1568
Wrong Address                                    1005
Name: count, dtype: int64

### Handling Missing Values in Incomplete Ride Reasons

The following code replaces missing values in the `Canceled_Rides_by_Customer` column with `"Not Canceled_Rides_by_Customer"`.

In [111]:
df['Canceled_Rides_by_Customer'] = (
    df['Canceled_Rides_by_Customer']
    .fillna('Not Cancelled by Customer')
)

In [112]:
df[['Driver_Ratings', 'Customer_Rating']].isnull().sum()*100

Driver_Ratings     3905700
Customer_Rating    3905700
dtype: int64

In [114]:
df['Driver_Ratings'].value_counts(dropna=False)

Driver_Ratings
NaN    39057
3.8     3313
3.9     3274
3.1     3273
4.2     3259
3.3     3249
3.5     3235
4.7     3232
4.1     3231
4.5     3214
3.7     3208
4.4     3185
4.6     3183
4.8     3176
4.3     3164
3.2     3161
4.0     3160
3.4     3130
3.6     3124
4.9     3105
3.0     1560
5.0     1531
Name: count, dtype: int64

### Handling Missing Values in Ratings

The following code replaces missing values in the `Driver_Ratings` and `Customer_Rating` columns with their respective mean values.

In [115]:
df['Driver_Ratings'] = df['Driver_Ratings'].fillna(df['Driver_Ratings'].mean())
df['Customer_Rating'] = df['Customer_Rating'].fillna(df['Customer_Rating'].mean())

### Correlation Analysis: Ride Distance vs Driver Ratings

The following code calculates the correlation between ride distance and driver ratings

In [116]:
df[['Ride_Distance','Driver_Ratings']].corr()

                Ride_Distance  Driver_Ratings
Ride_Distance        1.000000       -0.005146
Driver_Ratings      -0.005146        1.000000

### Standardizing Column Names

The following code cleans and standardizes the dataset's column names

In [117]:
df.columns = df.columns.str.strip().str.replace(" ", "_")

In [118]:
df.columns

Index(['Date', 'Time', 'Booking_ID', 'Booking_Status', 'Customer_ID',
       'Vehicle_Type', 'Pickup_Location', 'Drop_Location',
       'Canceled_Rides_by_Customer', 'Canceled_Rides_by_Driver',
       'Incomplete_Rides', 'Incomplete_Rides_Reason', 'Booking_Value',
       'Payment_Method', 'Ride_Distance', 'Driver_Ratings', 'Customer_Rating',
       'Vehicle_Images'],
      dtype='object')

In [120]:
df['Payment_Method'].value_counts(dropna=False)

Payment_Method
NaN            39057
Cash           35022
UPI            25881
Credit Card     2435
Debit Card       629
Name: count, dtype: int64

### Handling Missing Values in Payment Method

The following code replaces missing values in the `Payment_Method` column with `"Unknown"`

In [121]:
df['Payment_Method'] = df['Payment_Method'].fillna("Unknown")

In [122]:
df['Incomplete_Rides'].value_counts(dropna=False)

Incomplete_Rides
No     60041
NaN    39057
Yes     3926
Name: count, dtype: int64

### Handling Missing Values in Incomplete rides

The following code replaces missing values in the `Incomplete_Rides` column with `"No"`

In [123]:
df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna("No")

### After analysis and removing null values

In [124]:
df.isnull().sum()

Date                          0
Time                          0
Booking_ID                    0
Booking_Status                0
Customer_ID                   0
Vehicle_Type                  0
Pickup_Location               0
Drop_Location                 0
Canceled_Rides_by_Customer    0
Canceled_Rides_by_Driver      0
Incomplete_Rides              0
Incomplete_Rides_Reason       0
Booking_Value                 0
Payment_Method                0
Ride_Distance                 0
Driver_Ratings                0
Customer_Rating               0
Vehicle_Images                0
dtype: int64

In [125]:
df.dtypes

Date                          datetime64[ns]
Time                                  object
Booking_ID                            object
Booking_Status                        object
Customer_ID                           object
Vehicle_Type                          object
Pickup_Location                       object
Drop_Location                         object
Canceled_Rides_by_Customer            object
Canceled_Rides_by_Driver              object
Incomplete_Rides                      object
Incomplete_Rides_Reason               object
Booking_Value                          int64
Payment_Method                        object
Ride_Distance                          int64
Driver_Ratings                       float64
Customer_Rating                      float64
Vehicle_Images                        object
dtype: object

In [126]:
df.duplicated().sum()

np.int64(0)

In [127]:
df.describe()

,Date,Booking_Value,Ride_Distance,Driver_Ratings,Customer_Rating
count,103024,103024.000000,103024.000000,103024.000000,103024.000000
mean,2024-07-16 11:31:38.879678720,548.751883,14.189927,3.997457,3.998313
min,2024-07-01 00:00:00,100.000000,0.000000,3.000000,3.000000
25%,2024-07-08 18:41:00,242.000000,0.000000,3.800000,3.800000
50%,2024-07-16 11:23:00,386.000000,8.000000,3.997457,3.998313
75%,2024-07-24 05:18:00,621.000000,26.000000,4.200000,4.200000
max,2024-07-31 23:58:00,2999.000000,49.000000,5.000000,5.000000
std,NaN,536.541221,15.776270,0.454526,0.456199

### Final EDA Insights:
Booking values show high variability, indicating dynamic pricing based on ride conditions.
Ride distance contains some zero values, which may indicate cancellations or data recording issues.
Driver and customer ratings are concentrated around 4.0, showing generally positive feedback with low variation.
Date column does not have statistical deviation since it is a datetime field.

### Date Feature Extraction

The following code extracts useful date-related features from the `Date` column

In [128]:
df['year'] = df['Date'].dt.year
df['month'] = df['Date'].dt.month
df['day'] = df['Date'].dt.day
df['weekday'] = df['Date'].dt.day_name()

In [129]:
df.head
display(df)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,...,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle_Images,year,month,day,weekday
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,Not Cancelled by Customer,Personal & Car related issue,...,444,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/14183/1...,2024,7,26,Friday
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,158,Cash,13,4.100000,4.000000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,25,Thursday
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,386,UPI,40,4.200000,4.800000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,30,Tuesday
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,Driver is not moving towards pickup location,Not Cancelled by Driver,...,384,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/6839/68...,2024,7,22,Monday
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,Not Cancelled by Customer,Not Cancelled by Driver,...,822,Credit Card,45,4.000000,3.000000,https://cdn-icons-png.flaticon.com/128/3202/32...,2024,7,2,Tuesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103019,2024-07-31 09:06:00,09:06:00,CNR9488489435,Success,CID371654,Prime Plus,Richmond Town,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,111,Cash,41,3.600000,3.800000,https://cdn-icons-png.flaticon.com/128/11409/1...,2024,7,31,Wednesday
103020,2024-07-31 15:12:00,15:12:00,CNR3151743100,Success,CID334158,Auto,Vijayanagar,Richmond Town,Not Cancelled by Customer,Not Cancelled by Driver,...,1097,UPI,17,4.300000,3.300000,https://cdn-icons-png.flaticon.com/128/16526/1...,2024,7,31,Wednesday
103021,2024-07-31 13:59:00,13:59:00,CNR1286151233,Success,CID113188,Prime SUV,Bannerghatta Road,JP Nagar,Not Cancelled by Customer,Not Cancelled by Driver,...,2201,Cash,37,3.600000,3.200000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,31,Wednesday
103022,2024-07-31 14:56:00,14:56:00,CNR2027162035,Success,CID118301,eBike,Indiranagar,Magadi Road,Not Cancelled by Customer,Not Cancelled by Driver,...,267,UPI,47,3.400000,3.100000,https://cdn-icons-png.flaticon.com/128/6839/68...,2024,7,31,Wednesday
103023,2024-07-31 13:57:00,13:57:00,CNR9770709721,Success,CID217959,Auto,Ulsoor,Hennur,Not Cancelled by Customer,Not Cancelled by Driver,...,462,UPI,3,4.800000,4.400000,https://cdn-icons-png.flaticon.com/128/16526/1...,2024,7,31,Wednesday

### Outlier Detection Using IQR Method

The following code identifies outliers in all numerical columns using the Interquartile Range (IQR) method

In [138]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

for col in numeric_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col}: {len(outliers)} outliers")

Booking_Value: 8468 outliers
Ride_Distance: 0 outliers
Driver_Ratings: 9469 outliers
Customer_Rating: 9636 outliers

### Calculating IQR Boundaries for Booking Value

The following code calculates the lower and upper bounds used to identify outliers in the `Booking_Value` column using the Interquartile Range (IQR) method.

In [139]:
Q1 = df['Booking_Value'].quantile(0.25)
Q3 = df['Booking_Value'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(lower, upper)

-326.5 1189.5

### Identifying High-Fare Rides

The following code filters rides with a booking value greater than the upper outlier threshold (`1189.5`) and displays their booking value and ride distance.

In [140]:
high_fare = df[df["Booking_Value"] > 1189.5]

print(high_fare[["Booking_Value", "Ride_Distance"]].head())

    Booking_Value  Ride_Distance
19           2014             33
28           2183             20
49           2936             34
64           1310              0
78           2208             40

In [141]:
print(len(high_fare))

8468

### Analyzing Zero-Distance Rides

The following code identifies rides where the ride distance is recorded as `0` and displays their booking status, booking value, and ride distance.

In [142]:
df[df["Ride_Distance"] == 0][
    ["Booking_Status", "Booking_Value", "Ride_Distance"]
].head(20)

          Booking_Status  Booking_Value  Ride_Distance
0     Canceled by Driver            444              0
3   Canceled by Customer            384              0
7     Canceled by Driver            344              0
8       Driver Not Found            839              0
9     Canceled by Driver            893              0
13    Canceled by Driver            427              0
16      Driver Not Found            366              0
22    Canceled by Driver            909              0
29  Canceled by Customer            604              0
30      Driver Not Found            802              0
32  Canceled by Customer            120              0
36    Canceled by Driver            783              0
37    Canceled by Driver            995              0
39    Canceled by Driver            170              0
41    Canceled by Driver           1130              0
46      Driver Not Found            594              0
53      Driver Not Found            162              0
56    Canceled by Driver            543              0
61      Driver Not Found            565              0
62    Canceled by Driver            276              0

### Average Booking Value by Booking Status

The following code calculates the average booking value for each booking status and sorts the results in descending order.

In [143]:
df.groupby("Booking_Status")["Booking_Value"].mean().sort_values(ascending=False)

Booking_Status
Canceled by Driver      552.426332
Canceled by Customer    549.661968
Success                 548.415073
Driver Not Found        543.245654
Name: Booking_Value, dtype: float64

In [130]:
df['Date'].min()   # first ride

Timestamp('2024-07-01 00:00:00')

In [131]:
df['Date'].max()   # last ride

Timestamp('2024-07-31 23:58:00')

In [132]:
df.groupby(df['Date'].dt.month)['Booking_Value'].sum()

Date
7    56534614
Name: Booking_Value, dtype: int64

### Exporting the Cleaned Dataset

The following code exports the cleaned and transformed dataset to an Excel file

In [135]:
df.to_excel("ola_ride_cleaned_data.xlsx", index=False)

In [136]:
print(df.shape)

(103024, 22)

In [137]:
df.head()

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,...,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle_Images,year,month,day,weekday
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,Not Cancelled by Customer,Personal & Car related issue,...,444,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/14183/1...,2024,7,26,Friday
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,158,Cash,13,4.100000,4.000000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,25,Thursday
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,386,UPI,40,4.200000,4.800000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,30,Tuesday
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,Driver is not moving towards pickup location,Not Cancelled by Driver,...,384,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/6839/68...,2024,7,22,Monday
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,Not Cancelled by Customer,Not Cancelled by Driver,...,822,Credit Card,45,4.000000,3.000000,https://cdn-icons-png.flaticon.com/128/3202/32...,2024,7,2,Tuesday