### Import necessary packages

In [ ]:
import pandas as pd
import sqlite3

### Loading cleaned dataset using Pandas

In [ ]:
ola_data = pd.read_excel("ola_ride_cleaned_data.xlsx") 

print(ola_data.shape)
ola_data.head()

(103024, 22)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,...,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle_Images,year,month,day,weekday
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,Not Cancelled by Customer,Personal & Car related issue,...,444,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/14183/1...,2024,7,26,Friday
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,158,Cash,13,4.100000,4.000000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,25,Thursday
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,386,UPI,40,4.200000,4.800000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,30,Tuesday
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,Driver is not moving towards pickup location,Not Cancelled by Driver,...,384,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/6839/68...,2024,7,22,Monday
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,Not Cancelled by Customer,Not Cancelled by Driver,...,822,Credit Card,45,4.000000,3.000000,https://cdn-icons-png.flaticon.com/128/3202/32...,2024,7,2,Tuesday

## Create a Database in SQLite

In [ ]:
conn_sqlite = sqlite3.connect("olaride_db.sqlite")  # Creates a database file
cursor = conn_sqlite.cursor()
print("SQLite connection established!")

SQLite connection established!

## Create a Table in SQLite

In [ ]:
cursor.execute("""
    CREATE TABLE IF NOT EXISTS ride_data (
        Date DATETIME,
    Time VARCHAR(20),
    Booking_ID VARCHAR(50) PRIMARY KEY,
    Booking_Status VARCHAR(50),
    Customer_ID VARCHAR(50),
    Vehicle_Type VARCHAR(50),
    Pickup_Location VARCHAR(100),
    Drop_Location VARCHAR(100),
    Canceled_Rides_by_Customer VARCHAR(100),
    Canceled_Rides_by_Driver VARCHAR(100),
    Incomplete_Rides VARCHAR(100),
    Incomplete_Rides_Reason VARCHAR(255),
    Booking_Value INT,
    Payment_Method VARCHAR(50),
    Ride_Distance INT,
    Driver_Ratings FLOAT,
    Customer_Rating FLOAT,
    Vehicle_Images VARCHAR(255),
    year INT,
    month INT,
    day INT,
    weekday VARCHAR(20)
)
""")
conn_sqlite.commit()

print("Table 'ride_data' created successfully in SQLite!")

Table 'ride_data' created successfully in SQLite!

## Data Insertion

In [ ]:
ola_data.to_sql(
    "ride_data",
    conn_sqlite,
    if_exists="replace",
    index=False
)

print("Data inserted successfully!")

Data inserted successfully!

In [12]:
import numpy as np

ola_data = ola_data.replace({np.nan: None})

In [14]:
query = "SELECT COUNT(*) as total_rows FROM ride_data;"
result = pd.read_sql(query,conn_sqlite)

print(result)

   total_rows
0      103024

In [17]:
query = "SELECT * FROM ride_data LIMIT 5"

result = pd.read_sql(query, conn_sqlite)

display(result)

,Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,...,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle_Images,year,month,day,weekday
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,Not Cancelled by Customer,Personal & Car related issue,...,444,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/14183/1...,2024,7,26,Friday
1,2024-07-25 22:20:00,22:20:00,CNR2940424040,Success,CID225428,Bike,Magadi Road,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,158,Cash,13,4.100000,4.000000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,25,Thursday
2,2024-07-30 19:59:00,19:59:00,CNR2982357879,Success,CID270156,Prime SUV,Sahakar Nagar,Varthur,Not Cancelled by Customer,Not Cancelled by Driver,...,386,UPI,40,4.200000,4.800000,https://cdn-icons-png.flaticon.com/128/9983/99...,2024,7,30,Tuesday
3,2024-07-22 03:15:00,03:15:00,CNR2395710036,Canceled by Customer,CID581320,eBike,HSR Layout,Vijayanagar,Driver is not moving towards pickup location,Not Cancelled by Driver,...,384,Unknown,0,3.997457,3.998313,https://cdn-icons-png.flaticon.com/128/6839/68...,2024,7,22,Monday
4,2024-07-02 09:02:00,09:02:00,CNR1797421769,Success,CID939555,Mini,Rajajinagar,Chamarajpet,Not Cancelled by Customer,Not Cancelled by Driver,...,822,Credit Card,45,4.000000,3.000000,https://cdn-icons-png.flaticon.com/128/3202/32...,2024,7,2,Tuesday